Map<String, String> en = {
  'register': 'Register',
  'registration': 'Registration',
  'bad_format_phone_number': 'Invalid phone number format',
  'signin': 'Sign in',
  'logout': 'Logout',
  'view_without_registration': 'View without registration',
  'login': 'Login',
  'use_phone_number': 'Use phone number',
  'use_email': 'Use email',
  'no_profile': 'Don\'t have a profile yet?',
  'no_prfile_reg': 'Register!',
  'private_policy':
      'By registering, you agree to our Terms of Service and Privacy Policy',
  'enter_email': 'Enter Email',
  'enter_pass': 'Enter password',
  'confirm_password': 'Confirm password',
  'next': 'Next',
  'back': 'Back',
  'skip': 'Skip',
  'cancel': 'Cancel',
  'save': 'Save',
  'restore': 'Restore',
  'not_specified': 'Not specified',
  'already_reg': 'Already registered?',
  'enter_name_company': 'Please enter your company name',
  'enter_user_name': 'Please enter a name',
  'name_changed_later': 'The name can be changed later',
  'hint_company': 'ChUP Cafe Perekrestok',
  'hint_name': 'Amina',
  'user_activities_list': 'Specify where or who is interesting to work',
  'activities_change_later': 'Interests can be changed later',
  'company': 'Employer',
  'employee': 'Job seeker',
  'select_account_type': 'Select account type',
  'city_change_later': 'City can be changed later',
  'code_was_send': 'Code was sent to @phone',
  'send_code_again': 'Send code again',
  'send_code_again_time': 'Resend in: @time sec',
  'step': 'Step @current/@ all',
  'enter_verifi_code': 'Enter the 6-digit code',
  /* profile employee */
  'about_me': 'About me',
  'experience': 'Experience',
  'education': 'Education',
  'app_submitted': 'Submitted submissions',
  'list_your_skills': 'List your skills',
  'skills': 'Skills',
  'indicate_lang_you_speak': 'Indicate the languages ​​you speak',
  'languages': 'Languages',
  'indicate_your_interests': 'Indicate your interests',
  /* profile comany*/
  'specify_city': 'Specify the city',
  'address': 'Address',
  'address_hint': 'Enter your address',
  'city': 'City',
  'phone': 'Phone',
  'posittion': 'Position',
  'work_time': 'Working time',
  'payment': 'Payment',
  'about_company': 'About company',
  'delete_account': 'Delete account',
  'deleted_account': 'Account deleted',
  /* --------- */
  'your_account_was_deleted':
      'Your account was deleted earlier. \nDo you want to restore?',
  'register_to_continue': 'Register, \nto continue.',
  'fill_in_field': 'Fill in the field',
  'you_no_active_vacancy': 'You have no active vacancies, would like to',
  'create_quest': 'create?',
  'interests': 'Interests',
  /* vacancy */
  'vacancy_descript_hint':
      'You can not write contacts ( phone number ) otherwise the vacancy will not pass moderation',
  'vacancy_description': 'Vacancy Description',
  'similar_vacancies': 'Similar vacancies',
  'view_responses': 'View responses (@count units)',
  'will_respond': 'Respond',
  'vacancy_benefits': 'Keywords',
  'enter_text': 'Enter text',
  'name_company': 'Company name',
  'pay_amount': 'Amount to pay',
  'new_vacancy': 'New vacancy',
  'edit_data': 'Modifying data',
  'no_vacancies_available': 'No vacancies available',
  'send_for_verification': 'Send for verification',
  'add_vacancies_favorites': 'Add vacancies to favorites',
  'add_employee_favorites': 'Add an employee to your favorites',
  'add_vacancies_favorites_resp': 'You can come back to them later to respond.',
  'add_employee_favorites_resp': 'You can come back to them later to answer.',
  'chats': 'No posts yet',
  'chats_employee': 'Your chats with the employer will be located here',
  'chats_company': 'Your chats with the employee will be located here',
  'send_message_emploee':
      'You can write to the chat after the employer invites you',
  'send_message_company': 'Write to start a dialogue',
  'job_app': 'Job application',
  'job_vacancy': 'Job vacancy',
  'your_request_has_been_sent': 'Your request has been sent',
  'thanks': 'Thanks!',
  'write_messgae': 'Write a message ...',
  'no_responses_vacancy':
      'Here will be a list of vacancies that you have applied for previously.',
  'select_chat_start_messaging': 'Select a chat  to start messaging',
  'select_city': 'Choose city',
  'fill_field': 'Fill in the field',
  'hint_city': 'Almaty',
  'distance': '@distance km',
  'search_jobs': 'Search Jobs',
  /* filter */
  'employment_type': 'Employment type',
  'show': 'Show',
  'turn_on': 'Turn on',
  'location_radius': 'Location radius',
  'from': 'from',
  'before': 'before',
  'payments': 'Payment',
  'filter': 'Filter',
  'clear_all': 'Clear all',
  'gps_enable_header': 'Geodata is available.',
  'gps_enable':
      'To use this type of search, enable the geolocation service and grant permission to the browser.',
  'your_resp_vacan': 'You have already applied for the job',
  'sel_all': 'All',
  'sel_job': 'Choose a position',
  'rout_back': 'Come back',
  'delete_acc': 'Account deleted',
  'rejection_reason': 'Rejection reason: @text',
  'date_of_birth': 'Date of Birth',
  'type_employ': 'Employment type',
  'work_format': 'What kind of work format suits you best?',
  'close_vacancy': 'Close vacancy',
  'input_birth_day': 'Enter date of birth',
  'specify_address': 'Enter your address',
  'specify_position': 'Specify position',
  'publish': 'Publish',
};
