Map<String, String> ru = {
  'register': 'Зарегистрироваться',
  'registration': 'Регистрация',
  'bad_format_phone_number': 'Неверный формат телефонного номера',
  'signin': 'Войти',
  'logout': 'Выход',
  'view_without_registration': 'Просмотреть без регистрации',
  'login': 'Вход',
  'use_phone_number': 'Использовать номер телефона',
  'use_email': 'Использовать email',
  'no_profile': 'Еще нет профиля?',
  'no_prfile_reg': 'Регистрируйся!',
  'private_policy':
      'Регистрируясь, вы соглашаетесть с нашими Уcловиями пользования и Политикой конфедециальности',
  'enter_email': 'Введите Email',
  'enter_pass': 'Введите пароль',
  'confirm_password': 'Подтвердите пароль',
  'next': 'Далее',
  'back': 'Назад',
  'skip': 'Пропустить',
  'cancel': 'Отмена',
  'save': 'Сохранить',
  'restore': 'Восстановить',
  'not_specified': 'Не указан',
  'already_reg': 'Уже зарегистрированны?',
  'enter_name_company': 'Укажите название компании',
  'enter_user_name': 'Укажите имя',
  'name_changed_later': 'Имя можно изменить позже',
  'hint_company': 'ЧУП Кафе "Перекресток"',
  'hint_name': 'Амина',
  'user_activities_list': 'Укажите где или кем интересно работать',
  'activities_change_later': 'Интересы можно изменить позже',
  'company': 'Работодатель',
  'employee': 'Соискатель',
  'select_account_type': 'Выберите тип аккаунта',
  'select_city': 'Выберите гоород',
  'city_change_later': 'Город можно изменить позже',
  'code_was_send': 'Код был отправлен на @phone',
  'send_code_again': 'Отправить код еще раз',
  'send_code_again_time': 'Отправить повторно через: @time секнуд',
  'step': 'Шаг @current/@all',
  'enter_verifi_code': 'Введите 6-знаачный код',
  /* profile employee*/
  'about_me': 'Обо мне',
  'experience': 'Опыт',
  'education': 'Образование',
  'app_submitted': 'Поданные заявки',
  'list_your_skills': 'Укажите свои навыки',
  'skills': 'Навыки',
  'indicate_lang_you_speak': 'Укажите языки которыми владеете',
  'languages': 'Языки',
  'indicate_your_interests': 'Укажите свои интереcы',
  /* profile comany*/
  'specify_city': 'Укажите город',
  'address': 'Адрес',
  'address_hint': 'Укажите адрес',
  'city': 'Город',
  'phone': 'Телефон',
  'posittion': 'Должность',
  'work_time': 'Рабочее время',
  'payment': 'Оплата',
  'about_company': 'О компании',
  'delete_account': 'Удалить аккаунт',
  'deleted_account': 'Аккаунт удален',
  /* --------- */
  'your_account_was_deleted':
      'Ваш аккаунт был удален ранее. \nЖелаете восстановить?',
  'register_to_continue': 'Зарегистрируйтесь, \nчтобы продолжить.',
  'fill_in_field': 'Заполните поле',
  'you_no_active_vacancy': 'У вас нет активных вакансий, желаете ',
  'create_quest': ' создать?',
  'interests': 'Интересы',
  /* vacancy*/
  'vacancy_descript_hint':
      'Нельзя писать контакты ( номер телефона ) иначе вакансия не пройдет модерацию',
  'vacancy_description': 'Описание вакансии',
  'similar_vacancies': 'Похожие вакансии',
  'view_responses': ' Просмотреть отклики (@count шт.)',
  'will_respond': ' Откликнутся',
  'vacancy_benefits': 'Ключевые слова',
  'enter_text': ' Введите текст',
  'name_company': ' Название компании',
  'pay_amount': ' Сумма оплаты',
  'new_vacancy': ' Новая вакансия',
  'edit_data': ' Изменение данных',
  'no_vacancies_available': ' Нет доступных вакансий',
  'send_for_verification': 'Отправить на проверку',
  'add_vacancies_favorites': 'Добавьте вакансии в избранное',
  'add_employee_favorites': 'Добавьте соискателя в избранное',
  'add_vacancies_favorites_resp':
      'Вы можете вернутся к ним позже, чтобы откликнуться',
  'add_employee_favorites_resp':
      'Вы можете вернутся к ним позже, чтобы ответить',
  'chats': 'Сообщений пока нет',
  'chats_employee': 'Здесь будут находиться ваши чаты с работодателем',
  'chats_company': 'Здесь будут находиться ваши чаты с соискателями',
  'send_message_emploee':
      'Вы можете писать в чат после того, как работодатель пригласит вас',
  'send_message_company': 'Напишите, чтобы начать диалог',
  'job_app': 'Отклик на вакансию',
  'job_vacancy': 'Вакансия',
  'your_request_has_been_sent': 'Ваша завявка отправлена',
  'thanks': 'Спасибо!',
  'write_messgae': 'Напишите сообщение...',
  'no_responses_vacancy':
      'Здесь будет список вакансий на которые вы откликнулись ранее',
  'select_chat_start_messaging': 'Выберите чат, чтобы начать обмен сообщениями',
  'fill_field': 'Заполните поле',
  'hint_city': 'Алматы',
  'distance': '@distance км',
  'search_jobs': 'Искать вакансии',
  /* filter */
  'employment_type': 'Тип занятости',
  'show': 'Показать',
  'turn_on': 'Включить',
  'location_radius': 'Радиус локации',
  'from': 'от',
  'before': 'до',
  'payments': 'Оплата',
  'filter': 'Фильтр',
  'clear_all': 'Очистить все',
  'gps_enable_header': 'Геоданные недоступны.',
  'gps_enable':
      'Чтобы воспользоваться данным типом поиска включите сервис геолокации и предоставьте разрешение браузеру.',
  'your_resp_vacan': 'Вы уже откликнулись на вакансию',
  'sel_all': 'Все',
  'sel_job': 'Выберите должность',
  'rout_back': 'Вернуться назад',
  'delete_acc': 'Аккаунт удален',
  'rejection_reason': 'Причина отказа: @text',
  'date_of_birth': 'Дата рождения',
  'type_employ': 'Тип занятости',
  'work_format': 'Какой формат работы вам более подходит?',
  'close_vacancy': 'Закрыть вакансию',
  'input_birth_day': 'Введите дату рождения',
  'specify_address': 'Укажите адрес',
  'specify_position': 'Укажите должность',
  'publish': 'Опубликовать',
};
